<?php

namespace Acme\ApiBundle\Repository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AvisRepository extends \Doctrine\ORM\EntityRepository{
     public function voted($page, $user) {
        $parameters = array('page' => $page, 'id' => $user);
        return $this->createQueryBuilder('v')
                        ->where('v.thread = :page')
                        ->innerJoin('v.author', 'u')
                        ->andWhere('u =  :id')
                        ->setParameters($parameters)
                        ->getQuery()
                        ->getResult();
    }
}
