<?php

namespace Acme\ApiBundle\Repository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends \Doctrine\ORM\EntityRepository{
    
    public function catDetails($id) {
        return $this->createQueryBuilder('c')
                        ->where('c.published = 1')
                        ->andWhere('c.id != :id')
                        ->setMaxResults(3)
                        ->orderBy('c.id', 'DESC')
                        ->setParameter('id', $id)
                        ->getQuery()
                        ->getResult();
    }
}
?>