<?php

namespace Acme\ApiBundle\Repository;

/**
 * OfferRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WishlistRepository extends \Doctrine\ORM\EntityRepository {

    public function wishByUser($user) {

        return $this->createQueryBuilder('w')
                        ->orderBy('w.id', 'DESC')
                        ->innerJoin('w.user', 'u')
                        ->where('u =  :user')
                        ->setParameter('user', $user)
                        ->getQuery()
                        ->getResult();
    }

    public function wishByUserAct($user, $idA) {

        return $this->createQueryBuilder('w')
                        ->orderBy('w.id', 'DESC')
                        ->innerJoin('w.user', 'u')
                        ->where('u =  :user')
                        ->innerJoin('w.activity', 'a')
                        ->andWhere('a =  :act')
                        ->setParameter('user', $user)
                        ->setParameter('act', $idA)
                        ->getQuery()
                        ->getOneOrNullResult();
    }

//    public function actByWishlist($idW) {
//        $activities = array();
//        $wishlist = $this->createQueryBuilder('w')
//                ->orderBy('w.id', 'DESC')
//                ->where('w.id = :idW')
//                ->setParameter('idW', $idW)
//                ->getQuery()
//                ->getOneOrNullResult();
//        foreach ($wishlist->getActivity() as $act) {
//            if ($act->getId()) {
//                array_push($activities, $act);
//            }
//        }
//        return array("name" => $wishlist->getName(),"idW" => $wishlist->getId(), "activities" => $activities);
//    }
//
//    public function AllActByWishlist($user) {
//
//        $wishlists_user = $this->wishByUser($user);
//        $activities = array();
//        foreach ($wishlists_user as $entity) {
//            array_push($activities, $entity->getActivity());
//        }
//        return $activities;
//    }

}
